---
title: "Day 3 Conditionals and Loops"
author: "Amritpal Sandhu"
date: "2022-08-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

### `if` Statements

```{r}
burrito <- 3

## Don't forget to run the line, ctrl enter

if (burrito > 2) {
  print("I love burritos!")
}
```

```{r}
my_ships <- c("Falcon", "X-wing", "Tie-Fighter", "Deathstar")

str_detect(my_ships, pattern = "r")

str_detect(my_ships, pattern = "x")

## Looks within each element to check is it's true or false

phrase <- "I love burritos"

if (str_detect(phrase, "love")) {
  print("I am a burrito fan.")
}

```

### `if-else` statement

```{r}
pika <- 89.1

if (pika > 60) {
  print ("mega pika")
} else {
  print ("normal pika")
}
```

```{r}
marmot <- 2.8

if (marmot < 0.5) {
  print("this is a small marmot")
} else if (marmot >= 0.5 & marmot < 3) {
  print("this is a medium marmot")
} else {
  print ("this is a large marmot")
}
```


### Example of the `%in%` operator
```{r}
## We only want the row with Tatooine and get rid of everything else

tatooine_characters <- starwars |> 
  filter(homeworld == "tatooine")

# Use the %in% operator to check multiple positive matches

tatooine_endor_naboo <- starwars |> 
  filter(homeworld %in% c("tatooine", "naboo", "endor"))

## In words: does the value in the homeworld variable for that row exists IN that vector c("tatooine", "naboo", "endor")
```

